management:
  security:
     enabled: false

shell:
  ssh:
    enabled: false

server:
  port: 7080

application:
  id: halfpipeRouter

#has to be here so it can be picked up in @Value
#router:
#  cacheRefresh: 1100