---
- name: install docker/packer/ansible prereqs
  apt: name={{item}} state=present
  with_items:
    - python-pycurl
    - apt-transport-https
    - unzip
    - python-apt

- name: install ansible repo
  apt_repository: repo='ppa:rquillo/ansible' update_cache=yes

- name: install ansible
  apt: name=ansible state=present

- name: download packer
  get_url: url=https://dl.bintray.com/mitchellh/packer/0.6.0_linux_amd64.zip
           dest=/tmp/packer.zip
           sha256sum=3c3c2d5fff21e0ba9aa25a18fcdf8ec04fbbd2f7364c74d843124336d1d7b36c

- name: unzip packer
  command: unzip /tmp/packer.zip -d /tmp/packer_bin creates=/usr/local/bin/packer

- name: install packer
  shell: mv /tmp/packer_bin/* /usr/local/bin creates=/usr/local/bin/packer

#TODO: paramaterize /home/vagrant
- name: create build dir
  file: path=/home/vagrant/build state=directory
  tags:
    - sync

- name: copy packer configuration to docker server
  sudo: no
  synchronize: src=../packer dest=/home/vagrant/build recursive=yes delete=yes
  tags:
    - sync

- name: copy ansible files to docker server
  sudo: no
  synchronize: src=. dest=/home/vagrant/build/ansible recursive=yes delete=yes
  tags:
    - sync

- name: copy docker to docker server
  sudo: no
  synchronize: src=../docker dest=/home/vagrant/build recursive=yes delete=yes
  tags:
    - sync


#TODO: install pipework https://raw.githubusercontent.com/jpetazzo/pipework/master/pipework