#management.port=8081
server:
  port: 9080

shell:
  ssh:
    port: 3000

halfpipe:
  id: exampleFrontend
  prefix: /v1
  consul:
    clients:
      - exampleService

exampleService:
  ribbon:
    #listOfServers: 192.168.33.1:8080
    #NIWSServerListClassName: halfpipe.consul.loadbalancer.ConsulServerList

logging:
  level: INFO
  loggers:
    - org.springframework.boot:INFO
    - org.springframework.security:ERROR
    - com.netflix.hystrix.HystrixCommand:DEBUG
