#management.port=8081
security:
  user:
    name: admin
    password: admin

endpoints:
  shutdown:
    enabled: true

application:
  id: exampleService
  prefix: /v1
  routes:
    - /hello
    - /posts

consul:
  tags:
    - api
    - example

swagger:
  apiVersion: 1
  basePath: http://localhost:8080/v1

logging:
  level: INFO
  loggers:
    - org.springframework.boot:INFO
    - org.springframework.security:ERROR
    - org.jboss.resteasy.springmvc.ResteasyHandlerMapping:ERROR

hello:
  defaultMessage: Hi from default config file
#  myThings: 1,2,a,b