#management.port=8081
security:
  user:
    name: admin
    password: admin

endpoints:
  shutdown:
    enabled: true

halfpipe:
  prefix: /v1
  consul:
    serviceName: exampleService
    tags:
      - api
      - example
  swagger:
    apiVersion: 1
    apiUrl: http://localhost:8080/api-docs
    basePath: http://localhost:8080/v1

logging:
  level: INFO
  loggers:
    - org.springframework.boot:INFO
    - org.springframework.security:ERROR

hello:
  defaultMessage: Hi from default config file
#  myThings: 1,2,a,b