#management.port=8081

halfpipe:
  urlMapping: /v1/*
#  urlMapping: /v1

logging:
  level: INFO
  loggers:
    - org.springframework.boot:INFO
    - org.springframework.security:ERROR

hello:
  defaultMessage: Hi from default config file