#management.port=8081
security:
  user:
    name: admin
    password: admin

endpoints:
  shutdown:
    enabled: true

halfpipe:
  prefix: /v1
  consul:
    serviceName: exampleService
    tags:
      - api
      - example

logging:
  level: INFO
  loggers:
    - org.springframework.boot:INFO
    - org.springframework.security:ERROR

hello:
  defaultMessage: Hi from default config file