helloText: "Hello from yaml config file"
helloInt: 5

appName: Example Halfpipe Java App
bannerFile: example.txt

myconfig: Myconfig from properties

http:
  port: 8080

logging:
  level: WARN
  loggers: org.springframework.security.web=INFO