helloText: "Hello from yaml config file new"
helloInt: 5
profiles: profile1, profile2

appName: Example Halfpipe Java App
bannerFile: example.txt

myconfig: Myconfig from properties

http:
  port: 8080

logging:
  level: WARN
  loggers: org.springframework.security.web=INFO